name: Gradle Test

on:
  push:
    branches:
      - main  # 在推送到 main 分支时运行工作流
  pull_request:
    branches:
      - main  # 在提交 pull request 到 main 分支时运行工作流

jobs:
  test:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 作为运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 从仓库中检出代码

      - name: Set up JDK 17
        uses: actions/setup-java@v4  # 设置 Java 环境
        with:
          distribution: 'temurin'    # 使用 Eclipse Temurin JDK
          java-version: '17'         # 设置 Java 版本为 17（可以修改为项目需要的版本）

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  # 赋予 gradlew 可执行权限

      - name: Run tests
        run: ./gradlew test  # 运行 Gradle 测试任务
